CREATE TABLE IF NOT EXISTS users
(
    id        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email     TEXT NOT NULL UNIQUE,
    pass_hash bytea NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_email ON users (email);

CREATE TABLE IF NOT EXISTS apps
(
    id     INT PRIMARY KEY,
    name   TEXT NOT NULL UNIQUE,
    secret TEXT NOT NULL UNIQUE
);
